name: Deploy Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
        
      - name: Build static site
        run: npx parcel build src/index.html
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-artifact # Ensure this is the correct name referenced in the deploy step
          path: dist/ # This is the output folder of your build (adjust if your build output is elsewhere)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages-artifact # This must match the artifact name from the upload step
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_path: ./github-pages-artifact # Ensure this points to the correct location of the downloaded artifact
